name: Android CI

on:
   workflow_dispatch :
   schedule :
    - cron: '0 0 * * *'
   push:
      branches: [ beta ]
   pull_request:
    branches: [ beta ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
  #  - name: Copy CI gradle.properties
  #   run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      
    - name: Build with Gradle
      run: ./gradlew build
      
#     - name: Upload apk
#       uses:  actions/upload-artifact@v2
#       with:
#        name: debug-apk
#        path: app/build/outputs/apk/debug/app-debug.apk
#  Used for uploading generated apk for future use
